title: <p style="text-align:center">Guillaume Salha</p>

logo: "https://github.com/GuillaumeSalha/GuillaumeSalha.github.io/blob/master/gs.png?raw=true"
logo2: "https://github.com/GuillaumeSalha/GuillaumeSalha.github.io/blob/master/logoxdeezer2.png?raw=true"

author: Guillaume Salha

description: >
  <p style="text-align:center"><b>Machine Learning Researcher</b>
  <br><br>
   <img src="https://github.com/GuillaumeSalha/GuillaumeSalha.github.io/blob/master/logoxdeezer2.png?raw=true" alt="Logo2" width="180" />
  <br> <br> <br>
  <u>Contact</u>
  <br><br>
  gsalha [at] deezer [dot] com
  <br><br>
  <a href="https://github.com/GuillaumeSalha">GitHub</a> - 
  <a href="https://www.linkedin.com/in/salhaguillaume/">LinkedIn</a> - 
  <a href="https://twitter.com/GuillaumeSalha">Twitter</a>
  <br><br>
  </p>

theme: jekyll-theme-minimal
